#!/usr/bin/env bash
# Auto-backup Stop hook: stage all changes, commit with an LLM-generated
# Conventional Commits message describing the diff, then push to origin.
#
# The message is produced by the `claude` CLI in headless mode (`-p`), which
# reuses Claude Code's existing OAuth auth — no ANTHROPIC_API_KEY required.
# --safe-mode skips CLAUDE.md/hooks/MCP/plugins so the nested call can't get
# steered into a tool call that stalls on a permission prompt with no TTY to
# answer it, and a hard timeout bounds worst-case hook duration. stderr and
# the exit code are logged to auto-backup.log (overwritten each run) so a
# failure leaves evidence instead of just silently falling back.
# If generation still yields nothing usable, we fall back to a message
# derived from `git diff --stat` so even the fallback describes what
# changed, not just when.
#
# AXON_AUTOBACKUP guards against recursion: the nested `claude -p` below runs
# in this same project and would otherwise fire this Stop hook again forever.
set -u

# Message is generated by `claude -p --model haiku` from the staged diff.
# Recursion guard — the nested claude inherits this and exits immediately.
[ -n "${AXON_AUTOBACKUP:-}" ] && exit 0

cd "${CLAUDE_PROJECT_DIR:-.}" || exit 0
git add -A

# Nothing staged -> nothing new to commit, but still push anything a previous
# run (or another hook that commits without pushing) left unpushed. Without
# this, a competing commit hook could starve the push forever.
if git diff-index --quiet HEAD; then
  git push origin HEAD >/dev/null 2>&1 || true
  exit 0
fi

log_file="${CLAUDE_PROJECT_DIR:-.}/.claude/hooks/auto-backup.log"

# Compact context for the model: filename stat + a bounded slice of the diff
# (keeps token cost low on large changes).
diff_ctx=$(
  git diff --cached --stat
  echo '---'
  git diff --cached | head -c 12000
)

# Capture the full reply into a variable, then post-process. (Don't pipe claude
# straight into head/sed — the model sometimes wraps the message in ``` code
# fences, and we need the whole reply to strip them reliably.)
raw=$(
  printf '%s' "$diff_ctx" | AXON_AUTOBACKUP=1 timeout 25 claude -p --model haiku \
    --safe-mode --no-session-persistence \
    "Write a single-line Conventional Commits message (format: type(scope): summary, all lowercase, max 70 chars) summarizing this staged git diff. Output ONLY the message text — no quotes, no markdown, no code fences." \
    2>"$log_file"
)
echo "exit=$?" >>"$log_file"

# Drop any ``` fence lines, take the first non-blank line, trim whitespace and
# any surrounding quotes/backticks.
msg=$(printf '%s\n' "$raw" \
  | grep -vE '^[[:space:]]*```' \
  | grep -m1 -E '[^[:space:]]' \
  | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' -e 's/^["`]*//' -e 's/["`]*$//')

# Fallback if the model returned nothing usable: derive a message from the
# diff itself instead of a bare timestamp.
if [ -z "$msg" ]; then
  names=$(git diff --cached --name-only | head -5 | paste -sd, -)
  extra=$(( $(git diff --cached --name-only | wc -l) - 5 ))
  [ "$extra" -gt 0 ] && names="$names (+$extra more)"
  msg="chore: update $names"
fi

git commit -m "$msg" >/dev/null 2>&1
git push origin HEAD >/dev/null 2>&1 || true
