; Script generated by Antigravity for the windowsapi app

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{D3B3E5B1-4C3D-4A5D-B6E7-F8D9C0A1B2C3}
AppName=Windows API
AppVersion=1.0.0
AppPublisher=Samuzziel
DefaultDirName={userappdata}\windowsapi
DefaultGroupName=Windows API
AllowNoIcons=yes
; Where the installer EXE will be saved
OutputDir=.\Output
OutputBaseFilename=windowsapi-setup
Compression=lzma
SolidCompression=yes
WizardStyle=modern
; Non-admin install (to AppData)
PrivilegesRequired=lowest

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
; The main executable
Source: "target\release\windowsapi.exe"; DestDir: "{app}"; Flags: ignoreversion
; Bundle config.toml if it exists in the project root, otherwise bundle config.example.toml but rename it to config.toml
#if FileExists("config.toml")
  Source: "config.toml"; DestDir: "{app}"; Flags: ignoreversion
#else
  Source: "config.example.toml"; DestDir: "{app}"; DestName: "config.toml"; Flags: ignoreversion
#endif

[Icons]
Name: "{group}\Windows API"; Filename: "{app}\windowsapi.exe"
Name: "{group}\{cm:UninstallProgram,Windows API}"; Filename: "{uninstallexe}"
Name: "{autodesktop}\Windows API"; Filename: "{app}\windowsapi.exe"; Tasks: desktopicon

[Run]
Filename: "{app}\windowsapi.exe"; Description: "{cm:LaunchProgram,Windows API}"; Flags: nowait postinstall skipifsilent

